name: Build Dev

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build_dev.yml
      - .github/workflows/reusable-build_docker.yml
      - Dockerfile
      - build.sh
  workflow_run:
    workflows: ["Build Tools"]
  schedule:
    # Midnight on Sundays
    - cron: '0 0 * * 0'

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  build_ros_jazzy:
    name: Build ROS Jazzy
    uses: ./.github/workflows/reusable-build_docker.yml
    with:
      base_image: osrf/ros:jazzy-desktop-full
      output_image: ghcr.io/chen-harrison/ros:jazzy
      runs-on: ubuntu-24.04
    secrets: inherit
  build_ros_kilted:
    name: Build ROS Kilted
    uses: ./.github/workflows/reusable-build_docker.yml
    with:
      base_image: osrf/ros:kilted-desktop-full
      output_image: ghcr.io/chen-harrison/ros:kilted
      runs-on: ubuntu-24.04
    secrets: inherit
  build_ros_rolling:
    name: Build ROS Rolling
    uses: ./.github/workflows/reusable-build_docker.yml
    with:
      base_image: osrf/ros:rolling-desktop-full
      output_image: ghcr.io/chen-harrison/ros:rolling
      runs-on: ubuntu-24.04
    secrets: inherit