name: Build Docker Images
# run-name: 

on:
  push:
    branches:
      - 'main'
    # paths:
    #   - 'Dockerfile'
    #   - 'build.sh'
  schedule:
    # Midnight on Sundays
    - cron: '0 0 * * 0'

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  build_ros_jazzy:
    name: Build ROS Jazzy
    uses: ./.github/workflows/reusable-build_docker.yml
    with:
      source_image: 'osrf/ros:jazzy-desktop-full'
      output_image: 'ghcr.io/chen-harrison/ros:jazzy'
      runs-on: ubuntu-24.04
    secrets: inherit